<?php

class ProjectTableSeeder extends Seeder
{
    public function run()
    {   
        $project = new Project();
        $project->user_id = User::find(1)->id;
        $project->client_id = Client::find(4)->id;
        $project->name = 'Batarang';
        $project->description = 'Bat-shaped boomerang.';
        $project->project_notes = '';
        $project->due_date = '2017-01-19';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'Payment Received';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Lucius Fox';
        $project->project_poc_email = '';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(3)->id;
        $project->client_id = Client::find(3)->id;
        $project->name = 'Billy club';
        $project->description = 'Strong, collapsible walking stick.';
        $project->project_notes = '';
        $project->due_date = '2016-12-16';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'In Progress';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Matt Murdock';
        $project->project_poc_email = 'mmurdock@nelsonmurdock.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(2)->id;
        $project->client_id = Client::find(1)->id;
        $project->name = 'Arc Reactor';
        $project->description = 'Compact power source.';
        $project->project_notes = '';
        $project->due_date = '2016-05-06';
        $project->project_submitted_date = '2016-03-26';
        $project->invoice_submitted_date = '2016-05-21';
        $project->invoice_approval_date = '2016-06-05';
        $project->pay_date = '';
        $project->project_status = 'Started';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Tony Stark';
        $project->project_poc_email = 'tstark@stark.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(1)->id;
        $project->client_id = Client::find(6)->id;
        $project->name = 'Shield';
        $project->description = 'Vibranium shield with red and white stripes and a white star in a blue circle in the middle.';
        $project->project_notes = '';
        $project->due_date = '2016-02-06';
        $project->project_submitted_date = '2016-02-01';
        $project->invoice_submitted_date = '2016-02-10';
        $project->invoice_approval_date = '2016-02-14';
        $project->pay_date = '';
        $project->project_status = 'Invoice Submitted';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Steve Rogers';
        $project->project_poc_email = 'srogers1920@aol.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(2)->id;
        $project->client_id = Client::find(6)->id;
        $project->name = 'Indestructable Motorcycle';
        $project->description = 'A bike that won\'t break in a little fender-bender.';
        $project->project_notes = '';
        $project->due_date = '2015-01-19';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'Payment Received';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Black Widow';
        $project->project_poc_email = 'natasha@nunya.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(3)->id;
        $project->client_id = Client::find(6)->id;
        $project->name = 'Expandable pants';
        $project->description = 'Pants that will expand without shredding, and shrink back.';
        $project->project_notes = '';
        $project->due_date = '2015-07-19';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'In Progress';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Bruce Banner';
        $project->project_poc_email = 'smash@msn.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(1)->id;
        $project->client_id = Client::find(4)->id;
        $project->name = 'Unhackable Database Application';
        $project->description = 'An application to store personal information about colleagues.';
        $project->project_notes = '';
        $project->due_date = '2015-08-01';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'Started';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Bruce Wayne';
        $project->project_poc_email = 'secrets@juno.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(3)->id;
        $project->client_id = Client::find(3)->id;
        $project->name = 'Text Reader';
        $project->description = 'Text reader capable of recognizing legal jargon.';
        $project->project_notes = '';
        $project->due_date = '2016-09-08';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'Project Submitted';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Matt Murdock';
        $project->project_poc_email = 'mmurdock@nelsonmurdock.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(2)->id;
        $project->client_id = Client::find(1)->id;
        $project->name = 'AI Backup';
        $project->description = 'Complex database, storage, and security.';
        $project->project_notes = '';
        $project->due_date = '2015-12-01';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'Invoice Approved';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Pepper Potts';
        $project->project_poc_email = 'ppotts@stark.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(1)->id;
        $project->client_id = Client::find(6)->id;
        $project->name = 'Trivia game';
        $project->description = 'Educational teaching tool on all significant events and people since end of WWII.';
        $project->project_notes = '';
        $project->due_date = '2011-08-30';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'In Progress';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Steve Rogers';
        $project->project_poc_email = 'srogers1920@aol.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(2)->id;
        $project->client_id = Client::find(6)->id;
        $project->name = 'Trivia game';
        $project->description = 'Educational teaching tool on all significant events and people since end of WWII.';
        $project->project_notes = '';
        $project->due_date = '2011-08-30';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'In Progress';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Steve Rogers';
        $project->project_poc_email = 'srogers1920@aol.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();

        $project = new Project();
        $project->user_id = User::find(3)->id;
        $project->client_id = Client::find(6)->id;
        $project->name = 'Trivia game';
        $project->description = 'Educational teaching tool on all significant events and people since end of WWII.';
        $project->project_notes = '';
        $project->due_date = '2011-08-30';
        $project->project_submitted_date = '';
        $project->invoice_submitted_date = '';
        $project->invoice_approval_date = '';
        $project->pay_date = '';
        $project->project_status = 'In Progress';
        $project->project_submitted = '';
        $project->invoice_submitted = '';
        $project->payment_received = '';
        $project->project_poc_name = 'Steve Rogers';
        $project->project_poc_email = 'srogers1920@aol.com';
        $project->project_poc_phone = '';
        $project->project_poc_address = '';
        $project->save();
        
    }
}